name: GitOps for development

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  gitops:
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.event.pull_request.title, '[dreamkast-releasebot]') }}
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        run: |
          docker login -u AWS -p $(aws ecr-public get-login-password --region us-east-1) public.ecr.aws

      - name: Build, tag, and push image to Amazon ECR
        id: ecr
        env:
          ECR_REGISTRY: public.ecr.aws/z5v6i5y3
          ECR_REPOSITORY: dreamkast-ecs
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOCKER_BUILDKIT: 1

        run: |
          echo REF ${{ github.ref }}
          echo HEAD REF ${{ github.head_ref }}
          echo SHA ${{ github.sha }}
          IMAGE_TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && IMAGE_TAG=$(echo $IMAGE_TAG | sed -e 's/^v//')
          [[ -n "${{ github.head_ref }}" ]] && IMAGE_TAG=${{ github.head_ref }}

          bash ./build-container.sh $IMAGE_TAG ${{ github.sha }}

      - name: Checkout dreamkast-infra
        uses: actions/checkout@v2
        with:
          repository: cloudopsdays/dreamkast-infra
          path: dreamkast-infra
          token:  ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Get target branch from IMAGE_TAG
        id: target-branch
        env:
          IMAGE_TAG: ${{ steps.ecr.outputs.IMAGE_TAG }}
        run: |
          if  [ ! -e ${{ github.head_ref }}  ]; then
            BRANCH=dk-$(cat $GITHUB_EVENT_PATH | jq -r ".number")
          else
            BRANCH=$(echo $IMAGE_TAG | sed s/_/-/)
          fi
          echo "::set-output name=BRANCH::${BRANCH}"

      - name: Update Kubernetes resources
        uses: cloudnativedaysjp/action-dreamkast-gitops@main
        with:
          base_dir: dreamkast-infra
          app_template_dir: manifests/app/dreamkast/overlays/template
          app_target_dir: manifests/app/dreamkast/overlays/development/${{ steps.target-branch.outputs.BRANCH }}
          argo_template_file: manifests/app/argocd-apps/template/dreamkast.yaml
          argo_target_file: manifests/app/argocd-apps/development/dreamkast-${{ steps.target-branch.outputs.BRANCH }}.yaml
          image: ${{ steps.ecr.outputs.IMAGE_WITH_SHA }}
          namespace: dreamkast-${{ steps.target-branch.outputs.BRANCH }}
          replacements: BRANCH=${{ steps.target-branch.outputs.BRANCH }},ENVIRONMENT=development

      - name: Commit files
        run: |
          cd dreamkast-infra/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add -A
          git commit -am "Bump docker tag (${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: cloudopsdays/dreamkast-infra
          directory: dreamkast-infra
          branch: main

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ github.event.action == 'opened' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Review app
            http://dreamkast-dk-${{ github.event.pull_request.number }}.dev.cloudnativedays.jp/
